---
title: "New Orleans Rain Gardens Data Viz"
output: html_notebook
---


#### Import & Preprocess Data

```{r setup, include=FALSE}
library(tidyverse)
library(scales)
```

```{r}
# import output data from process notebook
block_groups <- read.csv("../data/output/block_groups.csv")
gardens <- read.csv("../data/output/gardens_rainfall.csv")
crosswalk <- read.csv("../data/output/gardens_block_groups.csv")
```

```{r}
# merge the crosswalk of gradens and block groups to create binary output for whether a block group contains a garden location or not
block_groups <- merge(block_groups, crosswalk, all.x=TRUE) %>%
  mutate(garden_location = ifelse(!is.na(address),"Proposed Garden","No Proposed Garden")) %>%
  select(-address)

# reduce duplicates created by multiple gardens in one block group
block_groups <- unique(block_groups)
```

#### Plot Block Group Variables

```{r}
ggplot(block_groups, aes(x=percent_nonwhite, y=percent_pov, color=garden_location)) + 
  geom_jitter(alpha=.9) +
  # highlight garden locations
  scale_color_manual(values=c("lightgrey", "darkblue"), name="") + 
  # display averages
  geom_hline(yintercept=mean(block_groups$percent_pov, na.rm=TRUE), linetype = 'dashed', alpha=.4) + 
  geom_vline(xintercept=mean(block_groups$percent_nonwhite, na.rm=TRUE), linetype='dashed', alpha=.4) + 
  labs(x="Percent Non-White", y="Percent Below Poverty Line",
       title="Most rain gardens to serve majority-minority communities", subtitle="Orleans Parish, 2019 ACS") + 
  # print average values along trend line
  geom_text(aes(4,mean(percent_pov), label="Average: 24.8%", vjust=-.75), size=2) + 
  geom_text(aes(x=64.5,y=92, label="Average: 64.5%", vjust=-.75), size=2, angle=90) + 
  theme_minimal()
```

#### Plot Rain Gardens Monthly Average, Gallons

```{r}
ggplot(gardens, aes(x=monthly_gallons, y=reorder(address,monthly_gallons))) + 
  geom_bar(fill='lightblue', stat='identity') + 
  labs(x="", y="",
       title="Proposed rain gardens would each capture 4,000-37,000 gallons monthly",
       subtitle="NOAA Precipitation, 1947-2016") + 
  # add commas to each axes label
  scale_x_continuous(labels=label_comma()) + 
  # add average and display text for context
  geom_vline(xintercept=mean(gardens$monthly_gallons, na.rm=TRUE), linetype='dashed', alpha=.4) +
  geom_text(aes(x=13427, y=4, label="Average: 13,427", angle=90, vjust=-.75), size=2, color='lightblue') + 
  theme_minimal() + 
  # simplify y axis
  theme(panel.grid.major.y = element_blank(), axis.text.y=element_blank())
```

